# shellcheck shell=sh
# shellcheck disable=SC2034  # consumed by the installer, which sources this file
# GENERATED by `walk-blocker build` from search_rules.py and site.toml.
# Sourced by the shim installer, which symlinks guard.sh under each of these
# names -- but only the ones that actually resolve on the node. A shim named
# `ag` where ag is absent makes `command -v ag` succeed and silently changes
# how scripts probe for tools.
#
# The list is every name the rule table wraps minus `[shim].unwrapped_tools`,
# so it cannot drift from the case arms in guard.sh: both come from the same
# filtered tuple. locate, plocate and updatedb are deliberately absent from
# the table itself (see search_rules.py).
SG_WRAPPED_NAMES='find gfind bfs grep egrep fgrep zgrep rgrep rg fd fdfind tree du ugrep'
